version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}

  db:
    image: ${DB_IMAGE}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      - FLYWAY_USER=${DB_USER}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql

volumes:
  postgres_data:
